python3 GPT_TRUE_BATCH_A1_CALLBACK.py  --data_items="127,733,55,953" --batch_size=4 --total_timesteps=2000000 --retrain_from="./PPO/CT_S_127,733,55,953_RP_False_1224_163418_T_1000000.pt"
